apiVersion: v1
kind: Service
metadata:
  name: k8s-sample-app
  namespace: default
  labels:
    app: k8s-sample-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: k8s-sample-app